### ISSUE TITLE
Xref, Yref, and Zref in the Geometry function aren't actually being loaded into AVL

### ISSUE THREAD

**Issue by larze123** [renoelmendorp/AVLWrapper#3]
Hello, I've been messing around with this code and it seems like the Xref Yref and Zref, while they do write properly if you write geometry to a file, they don't actually make it to AVL. When I run it, Xref,Yref, and Zref remain 0 while it does its runs.

**Comment by renoelmendorp** [comment]
Hi Larze,
Thank you for catching this.
It indeed looks like that the {X,Y,Z}_cg in the case file override the geometry-set reference point. I will add some cod to catch this and make sure cases will default to values set in the geometry input file.
In the mean time, to continue your work, I would suggest you set the X_cg, Y_cg and Z_cg parameters in the cases.

**Comment by larze123** [comment]
Ah perfect, I appreciate it! It was driving me wild wondering where it was
being overridden. I even printed the output of geometry() to figure out if
the ref coordinates were working, and when they printed correctly to an
output file but wouldn't make it through to AVL, I thought I was going
crazy!

**Comment by renoelmendorp** [comment]
Should be fixed now, have fun!
