### ISSUE TITLE
Wrapper not handling different CL constraints

### ISSUE THREAD

**Issue by nberger8** [renoelmendorp/AVLWrapper#6]
I am attempting to define two different test cases, each with a different CL constraint, however the cl results I am getting for each test case are the same, which should be impossible considering each case is constrained to a different CL. The results I am getting appear to correspond to the case_1.

param_1 = Parameter(name='alpha', constraint='CL', value=0.66507)
case_1 = Case(name='Case 1', alpha=param_1)
param_2 = Parameter(name='alpha', constraint='CL', value=-0.26603)
case_2 = Case(name='Case 2', alpha=param_2)
all_cases = [case_1, case_2]
session = Session(geometry=geometry, cases=all_cases)

**Comment by renoelmendorp** [comment]
Hi nberger8,

I can't reproduce your issue:
```
result = session.get_results()
print(result['Case 1']['Totals']['Alpha'])
print(result['Case 2']['Totals']['Alpha'])
```

gives the expected result:
```
11.59195
-6.79682
```
